name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: write # to cache (actions/cache)

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  # cache:
  #   permissions:
  #     actions: write
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: ${{ fromJson(vars.MATRIX_NODE_VERSION) }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     # We need to cache some additional paths for Cypress
  #     # so call the npm-run-script action to install dependencies
  #     # and cache the additional paths
  #     - uses: kt-actions/npm-run-script@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         install-script: |
  #           npm install
  #           npx cypress install
  #         run-script: ''
  #         cache-delete: true # uncomment this line to delete the cache
  #         cache-additional-path: /home/runner/.cache/Cypress
  ci:
    uses: kt-workflows/npm-ci-cypress/.github/workflows/main.yml@v1
    with:
      # pass the matrix node version to the called workflow
      matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
      sonar-script: ''
      cache-additional-path: /home/runner/.cache/Cypress
      # cache-reset: true # uncomment this line to reset the cache
    # secrets:
    #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
