on:
  workflow_call:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  sonarqube:
    # Disabled at the moment
    if: ${{ 'true' == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
