name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  #     - run: |
  #         if [ -z ${{secrets.WORKFLOW_APP_ID }} ]; then
  #           echo "WORKFLOW_APP_ID is not set"
  #           exit 1
  #         fi
  dependabot:
    uses: kt-public/github-actions/.github/workflows/dependabot.yml@70331336ca6071f9ab280af77408e1dbd531804b
    secrets:
      WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      WORKFLOW_APP_PRIVATE_KEY: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
