name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  #     - run: |
  #         if [ -z ${{secrets.WORKFLOW_APP_ID }} ]; then
  #           echo "WORKFLOW_APP_ID is not set"
  #           exit 1
  #         fi
  dependabot:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: kt-public/github-actions/.github/workflows/dependabot.yml@5895d1e5e1a5f71cb9e3d19aea8826d95e1c29e7
    secrets:
      WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      WORKFLOW_APP_PRIVATE_KEY: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
