name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  #     - run: |
  #         if [ -z ${{secrets.WORKFLOW_APP_ID }} ]; then
  #           echo "WORKFLOW_APP_ID is not set"
  #           exit 1
  #         fi
  dependabot:
    uses: kt-public/github-actions/.github/workflows/dependabot.yml@f22d9e9d02846d781e22df70c139174c3068db01
    secrets:
      WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
