on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          bump-minor-pre-major: true # remove this to enable breaking changes causing 1.0.0 tag
          bump-patch-for-minor-pre-major: true # remove this to enable breaking changes causing 1.0.0 tag
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          echo "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "release-please"
          npm ci
          npm build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
